Paidikondala 1
WSU-CEG-6110-4410/AirViewer pull request #36
Opened 2022-04-28 05:24 UTC by paidikondala

As part of issue 10, implemented zoom-in and zoom-out functionalities

2022-04-28 20:49 UTC, aanuhya31 approved these changes
I see no issues with the code.

2022-04-29 19:32 UTC, sireeshanalabothu approved these changes

2022-04-29 23:39 UTC, sireeshanalabothu approved these changes
review completed and changes looks good.

2022-04-29 23:40 UTC, aanuhya31 requested changes

2022-04-29 23:40 UTC, aanuhya31 commented on src/main/java/edu/wright/airviewer2/AIRViewerController.java
> +		//zoom.set(zoom.get() * 1.1);
Please remove these comments

2022-04-29 23:40 UTC, aanuhya31 commented on src/main/java/edu/wright/airviewer2/AIRViewerController.java
> +		//zoom.set(zoom.get() / 1.1);
Please remove this too

2022-04-29 23:40 UTC, aanuhya31 commented on src/main/java/edu/wright/airviewer2/ZoomInZoomOut.java
> +	  */
Doxygen comments looks good

2022-04-29 23:44 UTC, paidikondala commented on src/main/java/edu/wright/airviewer2/AIRViewerController.java
> +		//zoom.set(zoom.get() * 1.1);
Removed the comments

2022-04-29 23:47 UTC, aanuhya31 approved these changes
Everything looks good now

2022-04-29 23:48 UTC, merged